[package]
name = "payday_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
payday_core = { path = "./payday_core" }
payday_node_lnd = { path = "./payday_node_lnd" }
bitcoin = { workspace = true }

[workspace]
members = [
    "payday_core",
    "payday_node_lnd"
]

[workspace.dependencies]
async-trait = "0.1.80"
bitcoin = "0.32.2"
