[package]
name = "payday_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
payday_core = { path = "./payday_core" }
payday_node_lnd = { path = "./payday_node_lnd" }
payday_btc = { path = "./payday_btc" }
bitcoin = { workspace = true }
serde = { workspace = true }
stream-ext = "0.2.4"
tokio-stream = { workspace = true }
futures = "0.3.30"

[workspace]
members = ["payday_btc", "payday_core", "payday_node_lnd"]

[workspace.dependencies]
async-trait = "0.1.80"
bitcoin = "0.32.2"
serde = { version = "1.0.203", features = ["derive"] }
tokio-stream = "0.1.14"
currencies = "0.4.1"
cqrs-es = "0.4.11"
