[package]
name = "payday_axum"
version = "0.1.0"
edition = "2024"

[dependencies]
payday_core = { path = "../payday_core" }
twelf = "0.15"
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
