[package]
name = "payday_core"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
bitcoin = { workspace = true }
serde = { workspace = true }
currencies = { workspace = true }
cqrs-es = { workspace = true }
stream-ext = "0.2.4"
tokio-stream = "0.1.14"
