name: Rust continuous integration

on:
  workflow_call:

  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: download protoc
        run: sudo apt-get install -y protobuf-compiler
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Run format check
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy -- -D warnings
